### PR TITLE
Add custom_http_headers feature

### PR DESCRIPTION
**Pull request by leeif**

### CODE REVIEW

**Comment by louy** [comment]
Thanks for contributing! Would you mind adding a test to show how this option would work?

**Comment by leeif** [comment]
@louy 
I have added a test of this.
Since custom_http_headers works only in a pro plan so I just put it into a comment here.
https://github.com/louy/terraform-provider-uptimerobot/pull/20/files#diff-1496caa481c76670a9af6b48cf8ec22fR182

**Comment by louy** [comment]
Shame that I can't run pro tests since I'm not really using UR that much

Hopefully that'll change at some point in the future

Thanks for contributing :)

**Comment by louy** [comment]
@all-contributors please add leeif for code, test

**Pull request merged**
