### PR TITLE
resource monitor: add support for interval attribute

### PR DESCRIPTION
**Pull request by nhamlh**

### CODE REVIEW

**Comment by nhamlh** [comment]
Hey @louy I would like to know that this PR is feasible to be merged :)

**Comment by louy** [comment]
Hi @nhamlh, Thanks for contributing!

Sorry I didn’t get a notification about this for some reason. 

Looks good but there might be a need for a minor change or two. I’ll take a closer look tonight.

**Comment by louy** [comment]
Would you be able to add a test case for setting a custom interval?

**Comment by nhamlh** [comment]
Sure @louy. However I'm not familiar with terraform test package yet so it would take me sometime to write the test :D

**Comment by louy** [comment]
I've added a test [here](https://github.com/louy/terraform-provider-uptimerobot/blob/39ed5dfd3706364710a9563fc257ae225ee9baac/uptimerobot/resource_uptimerobot_monitor_test.go#L131-L186) and merged your change. Thanks for contributing :)

**Pull request merged**
