### PR TITLE
sort alert_contacts

### PR DESCRIPTION
**Pull request by mtanda**
Fixes https://github.com/louy/terraform-provider-uptimerobot/issues/85

### CODE REVIEW

**Comment by louy** [comment]
Any chance you could add a small test for that? I.e. reproduce the pending changes issue and make sure it doesn't happen with the change?

**Comment by mtanda** [comment]
I'm not familiar with provider test. I change the uptime robot API interface code, should I mock API response to test it?

The uptime robot API response isn't guaranteed the alert_contacts order, sort by ID should fix the issue.
But if terraform local state is saved by different order, `terraform plan` will report diff.
Once user apply it, the order issue should be fixed.

**Comment by manuelvanrijn** [comment]
@louy would this test case cover it? I'm also not that familiar with go, and haven't got a pro plan to test the GitHub action out... I try using the threshold to determine if the order isn't changed.

```go
func TestUptimeRobotDataResourceMonitor_multiple_alert_contacts(t *testing.T) {
	var FriendlyName = "TF Test: multiple alert contacts"
	var Type = "http"
	var URL = "https://google.com"
	resource.Test(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckMonitorDestroy,
		Steps: []resource.TestStep{
			resource.TestStep{
				Config: fmt.Sprintf(`
				resource "uptimerobot_alert_contact" "first" {
					friendly_name = "#infrastructure"
					type = "slack"
					value = "https://slack.com/services/xxxx"
				}
				resource "uptimerobot_alert_contact" "second" {
					friendly_name = "#monitoring"
					type = "slack"
					value = "https://slack.com/services/xxxx"
				}
				resource "uptimerobot_monitor" "test" {
					friendly_name = "%s"
					type          = "%s"
					url           = "%s"
					alert_contact {
						id         = uptimerobot_alert_contact.first.id
						threshold  = 2
						recurrence = 0
					}
					alert_contact {
						id         = uptimerobot_alert_contact.second.id
						threshold  = 1
						recurrence = 0
					}
				}
				`, FriendlyName, Type, URL),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("uptimerobot_monitor.test", "friendly_name", FriendlyName),
					resource.TestCheckResourceAttr("uptimerobot_monitor.test", "type", Type),
					resource.TestCheckResourceAttr("uptimerobot_monitor.test", "url", URL),
					resource.TestCheckResourceAttr("uptimerobot_monitor.test", "alert_contact.#", "2"),
					resource.TestCheckResourceAttrSet("uptimerobot_monitor.test", "alert_contact.0.id"),
					resource.TestCheckResourceAttr("uptimerobot_monitor.test", "alert_contact.0.threshold", "2"),
					resource.TestCheckResourceAttr("uptimerobot_monitor.test", "alert_contact.0.recurrence", "0"),
					resource.TestCheckResourceAttrSet("uptimerobot_monitor.test", "alert_contact.1.id"),
					resource.TestCheckResourceAttr("uptimerobot_monitor.test", "alert_contact.1.threshold", "1"),
					resource.TestCheckResourceAttr("uptimerobot_monitor.test", "alert_contact.1.recurrence", "0"),
				),
			},
			resource.TestStep{
				ResourceName:      "uptimerobot_monitor.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}
```

**Comment by dlecan** [comment]
Do you need help to test/check the fix? I have a pro plan.

**Comment by louy** [comment]
Duplicate of #97

**Pull request closed without merging**
