### PR TITLE
Convert from dep to go modules and depend on terraform 0.12.3

### LINKED ISSUE #31: terraform 0.12 support
Running this provider with terraform v0.12.1 throws the following:

```
Error: Failed to instantiate provider "uptimerobot" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

Could we get [0.12 compatibility](https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html)?

### PR DESCRIPTION
**Pull request by jjungnickel**
Fixes #31

### CODE REVIEW

**Comment by jjungnickel** [comment]
Test builds available at https://github.com/jjungnickel/terraform-provider-uptimerobot/releases/tag/0.3.2-beta1

**Comment by louy** [comment]
Thanks for this! Awesome work

I'll take a look later this week and release a new version :)

**Comment by datachomp** [comment]
@jjungnickel the beta has been working great for me. Thank you and the team!

**Comment by drubin** [comment]
@louy any update on this?

**Comment by louy** [comment]
Yes it’s looking good. Just need to update the pipeline, specifically the dependency cashing step, and I haven’t used go modules yet so just trying to figure it out. Will merge as soon as I get that working

**Pull request closed without merging**
